#ifndef ERROR_HANDLER
#define ERROR_HANDLER
#include <stdio.h>

// Códigos de erro:
#define LEXICAL_ERROR_BAD_FORMATTING 1
#define LEXICAL_ERROR_UNKNOW_CHAR 2
#define SINTATICAL_ERROR_TOKEN_NOT_FOUND 3
#define SINTATICAL_ERROR_RESERVED_NOT_FOUND 4
#define SINTATICAL_ERROR_OPERATOR_NOT_FOUND 5
#define SINTATICAL_ERROR_IDENTIFICATOR_NOT_FOUND 6

void ERRO(FILE *arq, int err_code, int line_num);


#endif