COMPILER = gcc
CFLAGS = -Wall

make: 
	${COMPILER} ${CFLAGS} analisador_lexico.c ./data_structures/trie.c ./data_structures/hashing.c ./data_structures/vector.c -o teste

clean: 
	rm -f teste Analysed_Code.txt